const fs = require('fs');

let base64String = '/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEABsbGxscGx4hIR4qLSgtKj04MzM4PV1CR0JHQl2NWGdYWGdYjX2Xe3N7l33gsJycsOD/2c7Z//////////////8BGxsbGxwbHiEhHiotKC0qPTgzMzg9XUJHQkdCXY1YZ1hYZ1iNfZd7c3uXfeCwnJyw4P/Zztn////////////////CABEIAEgAIAMBIgACEQEDEQH/xAAvAAACAwEBAAAAAAAAAAAAAAACAwABBAUGAQEBAQEAAAAAAAAAAAAAAAAAAQID/9oADAMBAAIQAxAAAAD0NS6YNBCS4eWPTlxdpqS5luGupcvKzJK82DmQegGRqDIf/8QAJxAAAgEDAwIGAwAAAAAAAAAAAQIAAxESBCExBRUTFCIyYpEzUXH/2gAIAQEAAT8AYn9QM44WB2sLy9+YQGLXBntAxEYBj/IihQNorhHfKsN+BDXpLsayzx6Q3NUWislVlZHuBK6Fa95qVY1QQl9pQaoqrkg44M07+/04x6IZwcRKlAZkhYxwAup+pm+N0U/UQVs2yYYy3zgKCWlfUlXOE83Vh11cDgTueoEVrm8wPMe/ErIRYw9N+U7e9vyQ9NPOcfpeYHrn/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAEQESH/2gAIAQIBAT8AiZq6Ppkd/8QAGBEAAwEBAAAAAAAAAAAAAAAAARARIQD/2gAIAQMBAT8AGuHOGcDDZXF//9k=';
let outputFileName = 'myfile.jpeg';

let bufferData = Buffer.from(base64String, 'base64');
fs.writeFileSync(outputFileName, bufferData);